default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  port: 5432
  pool: 5

development:
  <<: *default
  host: backend-db
  username: nabthat-task
  password: nabthat-task
  database: nabthat-task

test:
  <<: *default
  host: backend-db-test
  username: nabthat-task-test
  password: nabthat-task-test
  database: nabthat-task-test
